use_frameworks!

platform :ios, '8.0'

target 'MRX264Pod_Example' do
  pod 'MRX264Pod', :path => '../'

  target 'MRX264Pod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
