use_frameworks!

platform :osx, '10.11'

target 'FFmpegTutorial-macOS' do
  pod 'MROpenSSLPod', :podspec => 'http://ifoxdev.hd.sohu.com/ffpods/20210913/MROpenSSLPod-macOS-1.1.1l.podspec'
  pod 'MRFFmpegPod', :path => '../MRFFmpegPod-macOS-4.4-openssl.podspec'
  # pod 'MRFFmpegPod', :podspec => 'http://ifoxdev.hd.sohu.com/ffpods/20210913/MRFFmpegPod-macOS-4.4-openssl.podspec'
end