#! /usr/bin/env bash
#
# Copyright (C) 2021 Matt Reach<qianlongxu@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# you can export GIT_HARFBUZZ_UPSTREAM=git@xx:yy/HARFBUZZ.git use your mirror
if [[ "$GIT_HARFBUZZ_UPSTREAM" != "" ]] ;then
    export GIT_UPSTREAM="$GIT_HARFBUZZ_UPSTREAM"
else
    export GIT_UPSTREAM=https://github.com/harfbuzz/harfbuzz.git
fi

export GIT_LOCAL_REPO=build/extra/harfbuzz
export GIT_COMMIT=8.3.0
export REPO_DIR=harfbuzz
export GIT_REPO_VERSION=8.3.0